/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * frontend-quiz-api
 */

export interface AnswerSubmission {
  /** The unique identifier of the selected answer option */
  answerId: string;
}
