/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * frontend-quiz-api
 */

export interface AnswerResult {
  /** An explanation of why the answer is correct or incorrect */
  explanation: string;
  /** Indicates if the submitted answer is correct */
  isCorrect: boolean;
}
