/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * frontend-quiz-api
 */

export interface AnswerOption {
  /** The unique identifier of the answer option */
  id: string;
  /** Indicates whether this option is the correct answer. This should only be revealed on the frontend after the user answers. */
  isCorrect: boolean;
  /** The text of the answer option */
  text: string;
}
