/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * frontend-quiz-api
 */

export * from './answerOption';
export * from './answerResult';
export * from './answerSubmission';
export * from './question';
export * from './quiz';
export * from './quizDetails';
export * from './quizResult';
export * from './userProfile';
