/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * frontend-quiz-api
 */

export interface NewQuizForUser {
  questionId: string;
  quizId: string;
  usersAnswerId: string;
}
