/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * frontend-quiz-api
 */

export interface NewQuizQuestionAnswerForUser {
  questionId: string;
  quizId: string;
  userAnswerId: string;
}
