/* eslint-disable */

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * frontend-quiz-api
 */
import type { AnswerOption } from './answerOption';

export interface Question {
  /** An optional code snippet related to the question */
  codeSnippet?: string;
  /** The unique identifier of the question */
  id: string;
  /** A list of answer options for the question */
  options: AnswerOption[];
  /** The text of the question */
  text: string;
}
