/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * frontend-quiz-api
 */

export interface QuizDetails {
  /** The unique identifier of the quiz */
  _id: string;
  /** A brief description of the quiz */
  description: string;
  /** Indicates whether the quiz contains premium (paid) content */
  isPaid: boolean;
  /** URL to the logo image for the quiz */
  logoUrl?: string;
  /** The title of the quiz */
  title: string;
  /** The total number of questions in the quiz */
  totalQuestions: number;
}
