/* eslint-disable */

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * frontend-quiz-api
 */
import type { Question } from './question';

export interface Quiz {
  /** The unique identifier of the quiz */
  _id: string;
  /** A brief description of the quiz */
  description: string;
  /** Indicates whether the quiz contains premium (paid) content */
  isPaid: boolean;
  /** URL to the logo image for the quiz */
  logoUrl?: string;
  questions?: Question[];
  /** The title of the quiz */
  title: string;
}
