/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * frontend-quiz-api
 */

export interface QuizResult {
  /** The unique identifier of the quiz */
  _id: string;
  isCompleted: boolean;
  /** The percentage of correct answers */
  progressPercentage: number;
  title: string;
  /** The total number of questions in the quiz */
  totalQuestions: number;
}
