/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * frontend-quiz-api
 */

export interface QuizResult {
  /** The percentage of correct answers */
  correctAnswersPercentage: number;
  /** The unique identifier of the quiz */
  quizId: string;
  /** The total number of questions in the quiz */
  totalQuestions: number;
}
