/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * frontend-quiz-api
 */

export interface QuizAnswerResult {
  _id: string;
  correctAnswer: string;
  isCorrect: boolean;
  questionId: string;
  questionText: string;
  userAnswer: string;
}
