/* eslint-disable */

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * frontend-quiz-api
 */
import type { QuizAnswerResult } from './quizAnswerResult';

export interface QuizResult {
  /** The unique identifier of the quiz */
  _id: string;
  answers: QuizAnswerResult[];
  /** The percentage of correct answers */
  quizId: string;
  /** The total number of questions in the quiz */
  quizTitle: string;
  totalQuestions: number;
}
