/* eslint-disable */

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * frontend-quiz-api
 */
import type { QuizResult } from './quizResult';

export interface UserProfile {
  /** The unique identifier of the user */
  _id: string;
  /** A list of quizzes completed by the user */
  completedQuizzes: QuizResult[];
  /** The date and time the user joined */
  joinedDate: string;
  /** The name of the user */
  name: string;
  telegramId: string;
}
