/* eslint-disable */

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * frontend-quiz-api
 */
import type { QuizResult } from './quizResult';

export interface UserProfile {
  /** A list of quizzes completed by the user */
  completedQuizzes: QuizResult[];
  /** The unique identifier of the user */
  id: string;
  /** The name of the user */
  name: string;
}
